name: Create GitHub Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: 1.x

      - name: Build and compile
        run: deno task compile

      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: pre-${{ github.run_number }}
          tag_exists_error: false
          message: "rolling release tag"
        
      - name: Pre-Release
        uses: softprops/action-gh-release@v1
        with:
          name: pre-${{ github.run_number }}
          tag_name: pre-${{ github.run_number }}
          prerelease: true
          files: |
            saig-node
            saig-node.exe